# Generated by Django 3.1.7 on 2021-06-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('creator', models.CharField(default='abedgh', max_length=100)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('SE', 'Software Engineering'), ('EE', 'Electrical Engineering'), ('CE', 'Chemical Engineering'), ('Ce', 'Civil Engineering'), ('ME', 'Mechanical Engineering')], default='SE', max_length=300, null=True)),
            ],
        ),
    ]
